### ISSUE TITLE
Error in Data Zip

### ISSUE THREAD

**Issue by laneja** [sashatrubetskoy/bri_market_access#1]
By way of an introduction I am a graduate student at the LSE. I am currently working on a number of BRI projects and I wanted to replicate your results. However I cannot open the data zip file as there is either an error message or in WinZIp the error message says that the file is empty. Can you offer any advice?

**Comment by a-trubetskoy** [comment]
I've re-uploaded the dataset and updated the link in README.md. Let me know if it works

**Comment by laneja** [comment]
Thank you, it's working prefectly as per the script.
